project:
  name: PoisonGuard
  version: "0.1"

dataset:
  name: CIFAR10
  num_classes: 10

model:
  name: ResNet18

training:
  batch_size: 128
  epochs: 10
  learning_rate: 0.001

tracking:
  mlflow_uri: "http://127.0.0.1:5000"
